services:
  all:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
      - 8002:8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./:/workspace
    command: make all -j
  
